### ISSUE TITLE
Interface allows bit corruption if passed value different than 0 or 1

### ISSUE THREAD

**Issue by Sopel97** [TheLartians/bit_view#9]
https://github.com/TheLartians/BitView/blob/f0c5c7415b359149e9eaab3b515eadccec4e9586/include/bit_view.h#L49

This allows passing values with more than one set bit, but only one bit in the array is reset before setting. The type of the parameter should be `bool`.

**Comment by TheLartians** [comment]
Good catch, I was too worried about performance than correctness at  that point.
